### ISSUE TITLE
Tab should change when the header reaches at the top

### ISSUE THREAD

**Issue by Hiteshc29** [wayne900204/vertical_scrollable_tabview#1]
Right now even verticalScrollPosition: VerticalScrollPosition.begin is defined. It changes the tab when the header is in the middle of the screen. How I can change the tab while scrolling when the header reaches at the top only?

**Comment by wayne900204** [comment]
what is your flutter version?

**Comment by Hiteshc29** [comment]
> what is your flutter version?

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (2 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

**Comment by wayne900204** [comment]
OK.
Due to the recent midterm exam, I may need to start solving this problem after December.
SORRY～～～

**Comment by wayne900204** [comment]
Hi @Hiteshc29 
I updated the package version. 
Change the code to `verticalScrollPosition: VerticalScrollPosition.begin`. Then, the issue will be fix.
