### ISSUE TITLE
Can we use `GridView` instead of `ListView` for our Categories View?

### ISSUE THREAD

**Issue by aytunch** [wayne900204/vertical_scrollable_tabview#10]
Hi @wayne900204 thanks for authoring and maintaining this package :)
I am trying to make this UI using this package. Is it possible to use `GridView`?
<img width="323" alt="Screen Shot 2022-02-25 at 19 43 20" src="https://user-images.githubusercontent.com/6442915/155753603-84abd330-fb80-4e5c-a173-bfe5d5f8d478.png">

**Comment by wayne900204** [comment]
i would try to add this feature.

**Comment by aytunch** [comment]
@wayne900204 I made it work using `GridView`'s `gridDelegate` equal to `SliverGridDelegateWithFixedCrossAxisCount`.
Using other constructors of `GridView` did not work for some reason.

```
return VerticalScrollableTabView(
      tabController: tabController,
      listItemData: menuTitles,
      verticalScrollPosition: VerticalScrollPosition.begin,
      eachItemChild: (menuTitle, index) {
        return _DishesCategoryGrid(
          menuTitle: menuTitle,
          dishes: widget.dishes,
        );
      },
```


```
return GridView(
      // physics: const AlwaysScrollableScrollPhysics(),
      padding: const EdgeInsets.fromLTRB(7, 15, 7, 40),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        crossAxisSpacing: 5,
        // cacheExtent: 200,
        mainAxisSpacing: 8,
      ),
      shrinkWrap: true,
      primary: false,
```
