### ISSUE TITLE
Ability to wrap `eachItemChild` with `Scrollbar`

### ISSUE THREAD

**Issue by aytunch** [wayne900204/vertical_scrollable_tabview#12]
I think it would be nice to show a `Scrollbar` next to the scrolling area. Currently there is no way to do this.
Also if you are going to expose this functionality, please consider being able to customize the `Scrollbar` as well.
I tried wrapping `CustomScrollView` in the package with `ScrollBar` and it worked but the scroll bar extends to the `slivers` area (`TabBar`) too.

**vertical_scrollable_tabview.dart**
```
@override
  Widget build(BuildContext context) {
    return RectGetter(
      key: listViewKey,
      // NotificationListener 是一個由下往上傳遞通知，true 阻止通知、false 傳遞通知，確保指監聽滾動的通知
      // ScrollNotification => https://www.jianshu.com/p/d80545454944
      child: NotificationListener<ScrollNotification>(
        child: Scrollbar(                           //<-------------
           isAlwaysShown: true,
           CustomScrollView(
          controller: scrollController,
          slivers: [...widget._slivers, buildVerticalSliverList()],
        ),),
        onNotification: onScrollNotification,
      ),
    );
  }
```

**Comment by wayne900204** [comment]
Will it do the trick if you wrap a Scrollbar widget outside the VerticalScrollableTabView ?  ( I think it won't )
Because If I expose this functionality, it will be a big project.

**Comment by wayne900204** [comment]
Scrollbar and CustomScrollView parameters have been exposed to VerticalScrollableTabView.
