### ISSUE TITLE
Kotlin Gradle plugin version 1.5.20 and higher

### ISSUE THREAD

**Issue by FasrGitHub** [wayne900204/vertical_scrollable_tabview#21]
Hello! Faced the same issue while using your library. I think the error speaks for itself and comments are unnecessary here.

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':vertical_scrollable_tabview' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by wayne900204** [comment]
already fixed.
