### ISSUE TITLE
Why does the package need Platform Channels

### ISSUE THREAD

**Issue by aytunch** [wayne900204/vertical_scrollable_tabview#7]
I got an error on `generated_plugin_registrant.dart`
And I see that there are iOS and Android native communication.
Can we remove them?

**Comment by wayne900204** [comment]
@aytunch What version do you use?
0.0.4?
I just supported web application yesterday. I think maybe is this problem.
Can you give me a screenshot

**Comment by RizaldiWiratama** [comment]
i have same problem  about error on `generated_plugin_registrant.dart` in new version of package 0.0.4
this is the screenshot 
![image](https://user-images.githubusercontent.com/23089248/149862626-7578e7ab-f356-4f7e-8bba-7c5e2a0d1a2b.png)

but i still can get my app launch properly

**Comment by wayne900204** [comment]
I am trying to fixed it now. but i have no idea of this.
I just add it to Support Web
```
flutter create --template=plugin --platforms=web .
```

**Comment by wayne900204** [comment]
@aytunch @RizaldiWiratama 
I just fixed it. Can you try again in new version of package 0.0.5?

**Comment by RizaldiWiratama** [comment]
still same problem in 0.0.5 @wayne900204

**Comment by wayne900204** [comment]
@RizaldiWiratama @aytunch  I just fixed it. You can check in new version of package 0.0.6.
You can reopen this issue if there are any errors.
